#!/usr/bin/env python3
"""
backfill_platform_export_v43.py — Comprehensive indicator backfill for 2020-2024 v43 datasets.

Populates all remaining OHLCV-derived columns to match 2025 reference schema.

NOT populated (intentional omissions):
  trade_count          — requires external tick data (Alpaca/Polygon), not derivable from OHLCV
  pop, max_loss, ev, var_95, cvar_95, strategy_label, exit_signal, ps_* (11 cols)
                       — generated by strategy backtesting pipeline (Class B)
  PivotHigh..PivotSegmentVolatility (m5 only)
                       — all-NaN in 2025 m5 reference by design
  strong_pivot_slope_h/l, strong_pivot_bar_dist_h/l, bars_since_strong_pivot
                       — partially populated in 2025; deferred to pivot analytics pass

Columns computed (all TFs):
  log_return, ret_z, vol_energy, vol_ewma
  AnchoredVWAP
  TrendSeekerUp, TrendSeekerDown
  TurtleChn-Up, TurtleChn-Low
  bb_lower_dyn, bb_mu_dyn, bb_upper_dyn, bb_sigma_dyn, bandwidth, bw_expansion_rate
  MA, sma
  FRAMA, WeightedAlpha
  AccDistWill, AccDistWillMovAvg, OSC-Volume, WilderAccSwingIndex
  ATR_recon
  tod_sin, tod_cos
  friction_ok_5, friction_ok_10, friction_ok_20, friction_ok_40, friction_ok_60
  regime_persistence, price_stretch, ivr_zone, stretch_zone, reversal_score
  target_spot

Additional (m1, m15, h1 — skipped on m5 where Pivot cols are NaN by design):
  PivotHigh, PivotLow, Slope
  SlopeATR, PivotResidual, PivotResidualZ, PivotCurvatureProxy
  PivotResidualATR, PivotCurvatureATR
  PivotSegmentLengthBars, PivotSegmentLengthMinutes
  PivotSegmentResidualStd, PivotSegmentVolatility
  ATR_recon (recalculated from atr_pct × close)

Usage:
    python backfill_platform_export_v43.py
    python backfill_platform_export_v43.py --years 2022 2023 --timeframes m1 m5
    python backfill_platform_export_v43.py --force-all-targets
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
from scipy.stats import norm  # noqa — needed for FRAMA fallback only

# ── Project paths ─────────────────────────────────────────────────────────────
_SCRIPT_DIR   = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent.parent.parent

# Add project root to sys.path so scripts/indicators can be imported
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# ── Constants ─────────────────────────────────────────────────────────────────
YEARS      = [2020, 2021, 2022, 2023, 2024]
TIMEFRAMES = ["m1", "m5", "m15", "h1"]

TF_MINUTES = {"m1": 1, "m5": 5, "m15": 15, "h1": 60}

# Pivot analytics are all-NaN in 2025 m5 by design — skip for m5
PIVOT_SKIP_TFS = {"m5"}

# Columns this script targets (checked for unpopulated state)
TARGET_COLS = [
    "log_return", "ret_z", "vol_energy", "vol_ewma",
    "AnchoredVWAP",
    "TrendSeekerUp", "TrendSeekerDown",
    "TurtleChn-Up", "TurtleChn-Low",
    "bb_lower_dyn", "bb_mu_dyn", "bb_upper_dyn", "bb_sigma_dyn",
    "bandwidth", "bw_expansion_rate",
    "MA", "sma",
    "FRAMA", "WeightedAlpha",
    "AccDistWill", "AccDistWillMovAvg", "OSC-Volume", "WilderAccSwingIndex",
    "ATR_recon",
    "tod_sin", "tod_cos",
    "friction_ok_5", "friction_ok_10", "friction_ok_20",
    "friction_ok_40", "friction_ok_60",
    "regime_persistence", "price_stretch", "ivr_zone",
    "stretch_zone", "reversal_score",
    "target_spot",
]

PIVOT_COLS = [
    "PivotHigh", "PivotLow", "Slope",
    "SlopeATR", "PivotResidual", "PivotResidualZ", "PivotCurvatureProxy",
    "PivotResidualATR", "PivotCurvatureATR",
    "PivotSegmentLengthBars", "PivotSegmentLengthMinutes",
    "PivotSegmentResidualStd", "PivotSegmentVolatility",
]


# ── Logging ───────────────────────────────────────────────────────────────────

def setup_logger(log_path: Path) -> logging.Logger:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("backfill_platform_export_v43")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    fmt = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    fh  = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    fh.setFormatter(fmt)
    logger.addHandler(fh)
    sh  = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    logger.addHandler(sh)
    return logger


# ── Idempotency helper ────────────────────────────────────────────────────────

def _is_unpopulated(s: pd.Series) -> bool:
    """Column is unpopulated if entirely NaN (all-zero is valid data)."""
    return bool(s.isna().all())


# ══════════════════════════════════════════════════════════════════════════════
# Indicator implementations
# ══════════════════════════════════════════════════════════════════════════════

# ── Returns & Volatility ──────────────────────────────────────────────────────

def _compute_log_return(close: pd.Series) -> pd.Series:
    return np.log(close / close.shift(1)).astype(np.float32)

def _compute_vol_ewma(close: pd.Series, span: int = 64) -> pd.Series:
    r = np.log(close / close.shift(1))
    return np.sqrt((r ** 2).ewm(span=span, adjust=False).mean()).astype(np.float32)

def _compute_curvature_energy(close: pd.Series, span: int = 64) -> pd.Series:
    r    = np.log(close / close.shift(1))
    dr   = r.diff()
    d2r  = dr.diff()
    scl  = dr.abs().ewm(span=span, adjust=False).mean() + 1e-12
    kappa = (d2r / scl).ewm(span=max(8, span // 4), adjust=False).mean()
    return np.log1p(kappa.abs()).astype(np.float32)

def _compute_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
    h, l, c = df["high"], df["low"], df["close"]
    prev_c  = c.shift(1)
    tr = pd.concat([h - l, (h - prev_c).abs(), (l - prev_c).abs()], axis=1).max(axis=1)
    return tr.ewm(alpha=1 / period, adjust=False).mean()


# ── Bollinger Bands (dynamic) ─────────────────────────────────────────────────

def _compute_bb_dynamic(df: pd.DataFrame) -> pd.DataFrame:
    close, high, low = df["close"], df["high"], df["low"]
    vol_energy = _compute_curvature_energy(close)
    mu         = close.rolling(20, min_periods=1).mean()
    sigma      = close.rolling(20, min_periods=1).std(ddof=0).fillna(0)
    g          = (1.0 + vol_energy).clip(lower=1.0)
    sigma_dyn  = sigma * g
    bw         = sigma_dyn
    bw_min     = bw.rolling(100, min_periods=1).min()
    bw_max     = bw.rolling(100, min_periods=1).max()
    bb_pct     = 100 * (bw - bw_min) / (bw_max - bw_min + 1e-12)
    bw_exp     = bw.pct_change(5).fillna(0)
    res = pd.DataFrame(index=close.index)
    res["bb_mu_dyn"]        = mu.astype(np.float32)
    res["bb_sigma_dyn"]     = sigma_dyn.astype(np.float32)
    res["bb_lower_dyn"]     = (mu - 2.0 * sigma_dyn).astype(np.float32)
    res["bb_upper_dyn"]     = (mu + 2.0 * sigma_dyn).astype(np.float32)
    res["bandwidth"]        = bw.astype(np.float32)
    res["bw_expansion_rate"]= bw_exp.clip(-1, 1).astype(np.float32)
    return res


# ── Adaptive SMA & EMA ────────────────────────────────────────────────────────

def _compute_sma(close: pd.Series) -> pd.Series:
    log_ret    = np.log(close / close.shift(1))
    vol        = log_ret.rolling(64, min_periods=1).std()
    vol_med    = vol.rolling(256, min_periods=1).median()
    vol_ratio  = (vol / (vol_med + 1e-12)).clip(0.5, 3.0)
    alpha_med  = float((2.0 / (20.0 / vol_ratio + 1)).median())
    alpha_med  = float(np.clip(alpha_med, 0.01, 0.99))
    return close.ewm(alpha=alpha_med, adjust=False).mean().astype(np.float32)

def _compute_ma(close: pd.Series) -> pd.Series:
    """200-period EMA (long-trend reference)."""
    return close.ewm(span=200, adjust=False).mean().astype(np.float32)


# ── FRAMA ─────────────────────────────────────────────────────────────────────

def _compute_frama(close: pd.Series, window: int = 16) -> pd.Series:
    """
    Fractal Adaptive Moving Average.
    Vectorized rolling max/min pre-computation + sequential EMA pass.
    """
    c    = close.values.astype(np.float64)
    n    = len(c)
    half = window // 2
    s    = pd.Series(c, index=close.index)

    # Rolling extremes for each window half (vectorized)
    h2 = s.shift(1).rolling(half, min_periods=half).max().values
    l2 = s.shift(1).rolling(half, min_periods=half).min().values
    h1 = s.shift(half + 1).rolling(half, min_periods=half).max().values
    l1 = s.shift(half + 1).rolling(half, min_periods=half).min().values
    h3 = s.shift(1).rolling(window, min_periods=window).max().values
    l3 = s.shift(1).rolling(window, min_periods=window).min().values

    N1 = (h1 - l1) / half
    N2 = (h2 - l2) / half
    N3 = (h3 - l3) / window

    with np.errstate(divide="ignore", invalid="ignore"):
        num   = N1 + N2
        denom = np.where(N3 > 1e-10, N3, np.nan)
        ratio = np.where(num > 1e-10, num / denom, np.nan)
        D = np.where(ratio > 0, np.log(ratio) / np.log(2.0), 1.0)
    D     = np.where(np.isfinite(D), D, 1.0)
    alpha = np.clip(np.exp(-4.6 * (D - 1.0)), 0.01, 1.0)
    alpha = np.where(np.isfinite(alpha), alpha, 1.0)

    # Sequential EMA (FRAMA recurrence requires sequential pass)
    frama = c.copy()
    for i in range(1, n):
        if i >= window + half and np.isfinite(alpha[i]):
            frama[i] = alpha[i] * c[i] + (1.0 - alpha[i]) * frama[i - 1]

    return pd.Series(frama, index=close.index).astype(np.float32)


# ── WeightedAlpha ─────────────────────────────────────────────────────────────

def _compute_weighted_alpha(close: pd.Series, n: int = 252) -> pd.Series:
    """252-bar absolute price difference (scale-matched to 2025 reference)."""
    return close.diff(n).astype(np.float32)


# ── AnchoredVWAP ──────────────────────────────────────────────────────────────

def _compute_anchored_vwap(df: pd.DataFrame) -> pd.Series:
    """Rolling daily-reset VWAP."""
    ts   = pd.to_datetime(df["timestamp"])
    date = ts.dt.date
    pv   = df["close"] * df["volume"]
    cum_pv  = pv.groupby(date).cumsum()
    cum_vol = df["volume"].groupby(date).cumsum()
    return (cum_pv / (cum_vol + 1e-12)).astype(np.float32)


# ── Trend Seekers (PSAR-based) ────────────────────────────────────────────────

def _compute_trend_seekers(df: pd.DataFrame) -> pd.DataFrame:
    """TrendSeekerUp/Down = close price when PSAR trend is up/down, else NaN."""
    if "psar_trend" not in df.columns or _is_unpopulated(df["psar_trend"]):
        # Compute PSAR on the fly
        from scripts.indicators.psar_adaptive import compute_psar_full
        psar = compute_psar_full(df["high"], df["low"], df["close"])
        trend = psar["psar_trend"]
    else:
        trend = df["psar_trend"]

    close = df["close"]
    res = pd.DataFrame(index=df.index)
    res["TrendSeekerUp"]   = close.where(trend == 1.0).astype(np.float32)
    res["TrendSeekerDown"] = close.where(trend == -1.0).astype(np.float32)
    return res


# ── Donchian Channel ──────────────────────────────────────────────────────────

def _compute_donchian(df: pd.DataFrame, window: int = 20) -> pd.DataFrame:
    res = pd.DataFrame(index=df.index)
    res["TurtleChn-Up"]  = df["high"].rolling(window, min_periods=window).max().astype(np.float32)
    res["TurtleChn-Low"] = df["low"].rolling(window, min_periods=window).min().astype(np.float32)
    return res


# ── Williams A/D & AccDist ────────────────────────────────────────────────────

def _compute_acc_dist(df: pd.DataFrame) -> pd.DataFrame:
    close    = df["close"]
    high     = df["high"]
    low      = df["low"]
    prev_c   = close.shift(1).fillna(close.iloc[0])
    t_high   = pd.concat([high, prev_c], axis=1).max(axis=1)
    t_low    = pd.concat([low,  prev_c], axis=1).min(axis=1)
    diff     = close.diff().fillna(0.0)
    ad_val   = np.where(diff > 0, close - t_low,
               np.where(diff < 0, close - t_high, 0.0))
    ad_ser   = pd.Series(ad_val, index=close.index)
    acc      = ad_ser.cumsum()
    acc_ma   = acc.ewm(span=14, min_periods=1, adjust=False).mean()
    res = pd.DataFrame(index=df.index)
    res["AccDistWill"]       = acc.astype(np.float32)
    res["AccDistWillMovAvg"] = acc_ma.astype(np.float32)
    return res


# ── OSC-Volume ────────────────────────────────────────────────────────────────

def _compute_osc_volume(df: pd.DataFrame) -> pd.Series:
    """Volume oscillator: fast EMA(5) - slow EMA(20) raw difference."""
    vol      = df["volume"].astype(np.float64)
    fast_ema = vol.ewm(span=5,  adjust=False).mean()
    slow_ema = vol.ewm(span=20, adjust=False).mean()
    return (fast_ema - slow_ema).astype(np.float32)


# ── Wilder Accumulation Swing Index ──────────────────────────────────────────

def _compute_wilder_asi(df: pd.DataFrame) -> pd.Series:
    """Wilder's Accumulative Swing Index (simplified, no limit-move scaling)."""
    close  = df["close"].values.astype(np.float64)
    open_  = df["open"].values.astype(np.float64)
    high   = df["high"].values.astype(np.float64)
    low    = df["low"].values.astype(np.float64)
    n      = len(close)

    si  = np.zeros(n, dtype=np.float64)
    asi = np.zeros(n, dtype=np.float64)

    for i in range(1, n):
        pc   = close[i - 1]
        po   = open_[i - 1]
        R1   = abs(high[i] - pc)
        R2   = abs(low[i]  - pc)
        R3   = high[i] - low[i]
        R    = max(R1, R2, R3, 1e-10)
        num  = (close[i] - pc
                + 0.5 * (close[i] - open_[i])
                + 0.25 * (pc - po))
        si[i]  = num / R
        asi[i] = asi[i - 1] + si[i]

    return pd.Series(asi, index=df.index).astype(np.float32)


# ── ATR Recon ─────────────────────────────────────────────────────────────────

def _compute_atr_recon(df: pd.DataFrame) -> pd.Series:
    """Absolute ATR = atr_pct × close."""
    if "atr_pct" in df.columns and not _is_unpopulated(df["atr_pct"]):
        atr_pct = df["atr_pct"]
    else:
        atr_pct = _compute_atr(df) / df["close"]
    return (atr_pct * df["close"]).astype(np.float32)


# ── Time of Day ───────────────────────────────────────────────────────────────

def _compute_tod(df: pd.DataFrame) -> pd.DataFrame:
    """Cyclical time-of-day encoding over the regular session (9:30–16:00 ET)."""
    ts   = pd.to_datetime(df["timestamp"])
    mins = (ts.dt.hour - 9) * 60 + ts.dt.minute - 30  # minutes since 9:30
    frac = mins.clip(0, 389).astype(float) / 390.0
    res  = pd.DataFrame(index=df.index)
    res["tod_sin"] = np.sin(2 * np.pi * frac).astype(np.float32)
    res["tod_cos"] = np.cos(2 * np.pi * frac).astype(np.float32)
    return res


# ── Friction OK flags ─────────────────────────────────────────────────────────

def _compute_friction_ok(df: pd.DataFrame) -> pd.DataFrame:
    """Binary flags: fraction of last N bars with spread_ratio < 0.01."""
    if "spread_ratio" in df.columns and not _is_unpopulated(df["spread_ratio"]):
        sr = df["spread_ratio"].fillna(1.0)
    else:
        mid = (df["high"] + df["low"]) / 2 + 1e-12
        sr  = (df["high"] - df["low"]) / mid
    liquid = (sr < 0.01).astype(float)
    res = pd.DataFrame(index=df.index)
    for w in (5, 10, 20, 40, 60):
        ok = (liquid.rolling(w, min_periods=1).mean() >= 0.8).astype(np.float32)
        res[f"friction_ok_{w}"] = ok
    return res


# ── Regime Persistence ────────────────────────────────────────────────────────

def _compute_regime_persistence(df: pd.DataFrame) -> pd.Series:
    """
    Running count of consecutive bars in the same PSAR trend direction,
    normalised by rolling max count (∈ [0, 1]).
    """
    if "psar_trend" in df.columns and not _is_unpopulated(df["psar_trend"]):
        trend = df["psar_trend"].fillna(1.0)
    else:
        from scripts.indicators.psar_adaptive import compute_psar_full
        psar  = compute_psar_full(df["high"], df["low"], df["close"])
        trend = psar["psar_trend"]

    t   = trend.values
    cnt = np.ones(len(t), dtype=np.float64)
    for i in range(1, len(t)):
        if t[i] == t[i - 1]:
            cnt[i] = cnt[i - 1] + 1.0
    cnt_ser  = pd.Series(cnt, index=df.index)
    roll_max = cnt_ser.rolling(252, min_periods=1).max()
    return (cnt_ser / roll_max).clip(0.0, 1.0).astype(np.float32)


# ── Price Stretch & Zones ─────────────────────────────────────────────────────

def _compute_price_stretch(df: pd.DataFrame, bb: pd.DataFrame) -> pd.Series:
    """Normalised price position within Bollinger bands: (close - mu) / (2σ)."""
    mu    = bb["bb_mu_dyn"]
    sigma = bb["bb_sigma_dyn"]
    return ((df["close"] - mu) / (2.0 * sigma + 1e-8)).astype(np.float32)

def _compute_stretch_zone(price_stretch: pd.Series) -> pd.Series:
    """1 if |price_stretch| > 0.5 (outside Bollinger bands), else 0."""
    return (price_stretch.abs() > 0.5).astype(np.float32)

def _compute_ivr_zone(df: pd.DataFrame) -> pd.Series:
    """
    Vol percentile zone: 1=low, 2=mid, 3=high (rolling 252-bar vol_ewma quantiles).
    """
    vol = _compute_vol_ewma(df["close"])
    q33 = vol.rolling(252, min_periods=1).quantile(0.33)
    q67 = vol.rolling(252, min_periods=1).quantile(0.67)
    zone = np.where(vol < q33, 1, np.where(vol < q67, 2, 3))
    return pd.Series(zone, index=df.index).astype(np.float32)

def _compute_reversal_score(df: pd.DataFrame) -> pd.Series:
    """
    Reversal probability in [0, 1].
    Derived from breakout_score (∈ {-1, 0, +1}):
      reversal_score = (breakout_score × -0.5 + 0.5).clip(0, 1)
    High reversal_score when price is at or below lower band.
    """
    if "breakout_score" in df.columns and not _is_unpopulated(df["breakout_score"]):
        bs = df["breakout_score"]
    else:
        from scripts.indicators.reversal_stack import compute_reversal_stack
        stk = compute_reversal_stack(df["high"], df["low"], df["close"])
        bs  = stk["breakout_score"]
    return (-bs * 0.5 + 0.5).clip(0.0, 1.0).astype(np.float32)


# ── Target Spot ───────────────────────────────────────────────────────────────

def _compute_target_spot(df: pd.DataFrame, fwd_bars: int = 5) -> pd.Series:
    """5-bar forward log return × 100."""
    fwd  = df["close"].shift(-fwd_bars)
    ret  = np.where(
        (fwd > 0) & (df["close"] > 0),
        np.log(fwd / df["close"]) * 100.0,
        0.0,
    )
    return pd.Series(ret, index=df.index).astype(np.float32)


# ── Pivot Analytics ───────────────────────────────────────────────────────────

def _compute_pivot_analytics(df: pd.DataFrame, tf: str) -> pd.DataFrame:
    """
    Pivot detection + extended pivot analytics for m1, m15, h1.
    (m5 Pivot cols are all-NaN by design in 2025 reference — skip via caller.)
    """
    from scripts.indicators.psar_adaptive import compute_psar_full  # noqa

    close = df["close"]
    high  = df["high"]
    low   = df["low"]
    n     = len(close)
    mins_per_bar = TF_MINUTES[tf]

    # ── ATR for adaptive lookback ──
    if "atr_pct" in df.columns and not _is_unpopulated(df["atr_pct"]):
        atr14_pct = df["atr_pct"].values.astype(np.float64)
    else:
        atr14_pct = (_compute_atr(df, 14) / close).values.astype(np.float64)
    atr14_abs = atr14_pct * close.values.astype(np.float64)

    # Adaptive lookback: shorter in high vol, longer in low vol
    atr_s   = pd.Series(atr14_abs).rolling(200, min_periods=1).median().values
    atr_rat = np.clip(atr14_abs / (atr_s + 1e-12), 0.5, 3.0)
    base_lb = 5
    adap_lb = np.clip((base_lb / atr_rat).astype(int), 2, base_lb * 3)

    h = high.values.astype(np.float64)
    l = low.values.astype(np.float64)
    c = close.values.astype(np.float64)

    pivot_high = np.zeros(n, dtype=np.float32)
    pivot_low  = np.zeros(n, dtype=np.float32)
    slope_arr  = np.zeros(n, dtype=np.float64)

    last_price = c[0]
    last_idx   = 0

    for i in range(base_lb, n - base_lb):
        lb = int(min(adap_lb[i], i, n - i - 1))
        lb = max(lb, 2)

        # Local high pivot
        win_h = h[i - lb: i + lb + 1]
        if h[i] == win_h.max():
            pivot_high[i] = 1.0
            if i > last_idx:
                slope_arr[i] = (h[i] - last_price) / max(i - last_idx, 1)
                last_price    = h[i]
                last_idx      = i

        # Local low pivot
        win_l = l[i - lb: i + lb + 1]
        if l[i] == win_l.min():
            pivot_low[i] = 1.0
            if i > last_idx:
                slope_arr[i] = (l[i] - last_price) / max(i - last_idx, 1)
                last_price    = l[i]
                last_idx      = i

    slope_s = pd.Series(slope_arr, index=close.index)
    slope_s = slope_s.replace(0.0, np.nan).ffill().fillna(0.0)

    # Extended analytics
    ph_series = pd.Series(pivot_high, index=close.index)
    pl_series = pd.Series(pivot_low,  index=close.index)

    # ATR-normalised slope
    slope_atr = (slope_s / (atr14_abs + 1e-10)).astype(np.float32)

    # Bars since last pivot (high or low)
    any_pivot = (ph_series + pl_series).clip(0, 1)
    bars_since = np.zeros(n, dtype=np.float32)
    cnt = 0
    for i in range(n):
        if any_pivot.iloc[i] > 0:
            cnt = 0
        else:
            cnt += 1
        bars_since[i] = float(cnt)
    bars_since_s = pd.Series(bars_since, index=close.index)

    # Trend line residual: close minus linear interpolation between pivot prices
    # Approximation: close - (slope × bars_since + last_pivot_close)
    last_piv_price = np.full(n, c[0], dtype=np.float64)
    last_piv_idx_v = np.zeros(n, dtype=np.float64)
    last_piv_val   = c[0]
    last_piv_i     = 0
    for i in range(n):
        if any_pivot.iloc[i] > 0:
            last_piv_val = c[i]
            last_piv_i   = i
        last_piv_price[i] = last_piv_val
        last_piv_idx_v[i] = float(last_piv_i)

    trend_line = last_piv_price + slope_s.values * (np.arange(n) - last_piv_idx_v)
    residual   = c - trend_line
    resid_s    = pd.Series(residual, index=close.index)
    resid_std  = resid_s.rolling(252, min_periods=1).std() + 1e-12
    resid_z    = (resid_s / resid_std).astype(np.float32)
    resid_atr  = (resid_s / (atr14_abs + 1e-10)).astype(np.float32)

    # Curvature proxy: 2nd derivative of slope
    curve      = slope_s.diff().diff().fillna(0.0)
    curve_atr  = (curve / (atr14_abs + 1e-10)).astype(np.float32)

    # Segment stats (between consecutive pivots)
    seg_len_bars = bars_since_s + 1.0
    seg_len_mins = (seg_len_bars * mins_per_bar).astype(np.float32)

    # Segment residual std: rolling std within current segment (approx last N bars)
    seg_max_bars = int(seg_len_bars.max()) if len(seg_len_bars) > 0 else 20
    seg_max_bars = min(max(seg_max_bars, 5), 200)
    seg_resid_std = resid_s.rolling(seg_max_bars, min_periods=1).std().fillna(0.0)
    seg_vol = pd.Series(
        _compute_vol_ewma(close).values,
        index=close.index
    ).rolling(seg_max_bars, min_periods=1).mean()

    res = pd.DataFrame(index=close.index)
    res["PivotHigh"]               = ph_series.astype(np.float32)
    res["PivotLow"]                = pl_series.astype(np.float32)
    res["Slope"]                   = slope_s.astype(np.float32)
    res["SlopeATR"]                = slope_atr
    res["PivotResidual"]           = resid_s.astype(np.float32)
    res["PivotResidualZ"]          = resid_z
    res["PivotCurvatureProxy"]     = curve.astype(np.float32)
    res["PivotResidualATR"]        = resid_atr
    res["PivotCurvatureATR"]       = curve_atr
    res["PivotSegmentLengthBars"]  = seg_len_bars.astype(np.float32)
    res["PivotSegmentLengthMinutes"] = seg_len_mins
    res["PivotSegmentResidualStd"] = seg_resid_std.astype(np.float32)
    res["PivotSegmentVolatility"]  = seg_vol.astype(np.float32)
    return res


# ══════════════════════════════════════════════════════════════════════════════
# Per-file population driver
# ══════════════════════════════════════════════════════════════════════════════

def populate_file(
    path:            Path,
    tf:              str,
    force:           bool,
    logger:          logging.Logger,
) -> Dict:
    logger.info("  Loading %s", path)
    df = pd.read_csv(path, low_memory=False)
    rows_before = len(df)

    # Determine which targets need computing
    all_targets = list(TARGET_COLS)
    if tf not in PIVOT_SKIP_TFS:
        all_targets += PIVOT_COLS

    need = [c for c in all_targets if c in df.columns and (_is_unpopulated(df[c]) or force)]
    skip = [c for c in all_targets if c in df.columns and c not in need]

    logger.info("    %d target cols need population, %d already done", len(need), len(skip))
    if not need:
        logger.info("    All targets populated — skipping file.")
        return {"touched": 0, "skipped": len(skip)}

    # ── Compute all indicators ─────────────────────────────────────────────
    touched = 0

    def _write(col: str, values):
        nonlocal touched
        if col in df.columns and col in need:
            df[col] = values
            touched += 1

    # Returns & volatility
    log_ret    = _compute_log_return(df["close"])
    vol_ewma   = _compute_vol_ewma(df["close"])
    vol_energy = _compute_curvature_energy(df["close"])

    _write("log_return",  log_ret)
    _write("vol_ewma",    vol_ewma)
    _write("vol_energy",  vol_energy)
    _write("ret_z",       (log_ret / (vol_ewma + 1e-12)).astype(np.float32))

    # BB dynamic
    bb = _compute_bb_dynamic(df)
    for col in ["bb_mu_dyn", "bb_sigma_dyn", "bb_lower_dyn", "bb_upper_dyn",
                "bandwidth", "bw_expansion_rate"]:
        _write(col, bb[col])

    # SMA / MA
    _write("sma", _compute_sma(df["close"]))
    _write("MA",  _compute_ma(df["close"]))

    # FRAMA
    _write("FRAMA", _compute_frama(df["close"]))

    # WeightedAlpha
    _write("WeightedAlpha", _compute_weighted_alpha(df["close"]))

    # AnchoredVWAP
    _write("AnchoredVWAP", _compute_anchored_vwap(df))

    # TrendSeekers
    ts = _compute_trend_seekers(df)
    _write("TrendSeekerUp",   ts["TrendSeekerUp"])
    _write("TrendSeekerDown", ts["TrendSeekerDown"])

    # Donchian
    don = _compute_donchian(df)
    _write("TurtleChn-Up",  don["TurtleChn-Up"])
    _write("TurtleChn-Low", don["TurtleChn-Low"])

    # AccDist
    ad = _compute_acc_dist(df)
    _write("AccDistWill",       ad["AccDistWill"])
    _write("AccDistWillMovAvg", ad["AccDistWillMovAvg"])

    # OSC-Volume
    _write("OSC-Volume", _compute_osc_volume(df))

    # Wilder ASI
    _write("WilderAccSwingIndex", _compute_wilder_asi(df))

    # ATR_recon
    _write("ATR_recon", _compute_atr_recon(df))

    # Time of day
    tod = _compute_tod(df)
    _write("tod_sin", tod["tod_sin"])
    _write("tod_cos", tod["tod_cos"])

    # Friction OK flags
    fok = _compute_friction_ok(df)
    for col in ["friction_ok_5", "friction_ok_10", "friction_ok_20",
                "friction_ok_40", "friction_ok_60"]:
        _write(col, fok[col])

    # Regime persistence
    _write("regime_persistence", _compute_regime_persistence(df))

    # Price stretch & zones (uses BB already computed)
    ps = _compute_price_stretch(df, bb)
    _write("price_stretch", ps)
    _write("stretch_zone",  _compute_stretch_zone(ps))
    _write("ivr_zone",      _compute_ivr_zone(df))
    _write("reversal_score", _compute_reversal_score(df))

    # Target spot
    _write("target_spot", _compute_target_spot(df))

    # Pivot analytics (skip for m5)
    if tf not in PIVOT_SKIP_TFS:
        any_pivot_needed = any(c in need for c in PIVOT_COLS)
        if any_pivot_needed:
            logger.info("    Computing pivot analytics for %s…", tf)
            piv = _compute_pivot_analytics(df, tf)
            for col in PIVOT_COLS:
                if col in piv.columns:
                    _write(col, piv[col])

    # ── Validate & write ─────────────────────────────────────────────────
    assert len(df) == rows_before, "Row count changed during population"
    df.to_csv(path, index=False)
    logger.info("    Wrote %d columns → %s", touched, path.name)
    return {"touched": touched, "skipped": len(skip)}


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Backfill all remaining platform-export indicator columns for 2020-2024 v43 datasets."
    )
    ap.add_argument("--base-dir", default=str(_PROJECT_ROOT / "data" / "Datasetv4" / "v43"))
    ap.add_argument("--shells-dir", default=None)
    ap.add_argument("--years",      nargs="+", type=int, default=YEARS)
    ap.add_argument("--timeframes", nargs="+",           default=TIMEFRAMES)
    ap.add_argument(
        "--force-all-targets",
        action="store_true",
        help="Recompute all target columns even if already populated.",
    )
    ap.add_argument("--log",
        default=str(_PROJECT_ROOT / "logs" / "backfill_platform_export_v43.log"))
    ap.add_argument("--summary-json",
        default=str(_PROJECT_ROOT / "reports" / "population_audit"
                    / "backfill_platform_export_summary.json"))
    args = ap.parse_args()

    base_dir   = Path(args.base_dir)
    shells_dir = Path(args.shells_dir) if args.shells_dir else base_dir / "normalized_shells"
    log_path   = Path(args.log)
    sum_json   = Path(args.summary_json)
    sum_json.parent.mkdir(parents=True, exist_ok=True)

    logger = setup_logger(log_path)
    logger.info("=" * 70)
    logger.info("backfill_platform_export_v43.py")
    logger.info("base_dir  : %s", base_dir)
    logger.info("shells_dir: %s", shells_dir)
    logger.info("years     : %s", args.years)
    logger.info("timeframes: %s", args.timeframes)
    logger.info("force     : %s", args.force_all_targets)
    logger.info("=" * 70)

    summary: List[Dict] = []
    total_touched = 0

    for tf in args.timeframes:
        for year in args.years:
            p = shells_dir / str(year) / f"{tf}_dataset_v43_{year}.csv"
            if not p.exists():
                logger.warning("Missing: %s", p)
                continue

            logger.info("[%s %d]", tf, year)
            try:
                result = populate_file(p, tf, args.force_all_targets, logger)
                result.update({"year": year, "timeframe": tf, "file": str(p)})
                summary.append(result)
                total_touched += result["touched"]
            except Exception as exc:
                logger.error("  FAILED %s %d: %s", tf, year, exc, exc_info=True)
                summary.append({
                    "year": year, "timeframe": tf, "file": str(p),
                    "error": str(exc),
                })

    with open(sum_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    logger.info("=" * 70)
    logger.info("Backfill complete — total columns touched: %d", total_touched)
    logger.info("Summary JSON: %s", sum_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
